### ISSUE TITLE
[Bug 🐞]: Bottom attach point of Service Module 1 Mk2 Doesn't attach

### ISSUE THREAD

**Issue by MystLeissa** [zer0Kerbal/ProbiTronics#52]
### Brief description of your issue

I've tried everything I know to try to get the bottom attach point (the tin foil loaded one) to attach to stock parts by using the VAB; but at this point I'm considering the Part bugged, because It just won't let me attach anything there. For the record, I'm not talking about the Radial Attachment Points (those work fine) or the Top Attachment Point (Which also works fine). I'm talking about the part that's (supposedly) supposed to face the engines/fuel tanks.

### Steps to reproduce

Build a Rocket with a Mk I Command Pod, and a Service Module Mk1-2 and attempt to attach either a fuel tank or a engine on the bottom slot.

### Expected behavior

Attach in some capacity to the bottom point.

### Actual behavior

Attachable Part is greyed out and doesn't link (snap) to the grid.

### Environment

```shell
Mod: Downloaded it Today from CurseForge so I'd say latest prerelease
KSP: 1.12.3 (Final KSP Version)
Source: Curseforge
Installation Method: Manual Install
Operating System: Windows 10
```

### How did you download and install this?

CurseForge (download and manual installation)

**Comment by zer0Kerbal** [comment]
@MystLeissa Thank you for the report. I will work on this next instead of `Shielded PicoPort` :)

just probably a node I missed flipping. Will keep you updated here.

**Comment by zer0Kerbal** [comment]
fixed internally. Release incoming. Thank you @MystLeissa
